openapi : 3.0.0
info: 
  title : Social App
  descriptions : Our first social App     
  version: 0.1.9

servers:
  - url: http://localhost:8080/api/v1/user
    description: This is the base url for this api

components:
  securitySchemes:

   basicAuth:           
      type: http
      scheme: basic


   bearerAuth:            
      type: http
      scheme: bearer
      bearerFormat: JWT    

paths : 
  /insta:
    get: 
      summary: return instagram userName, follower and follow with Data.
      responses :
        '200' : #status code
          description: return an object with information about the user.
          content:
            application/json:
              schema:
                type : object
                properties:
                  userName:
                    type : string
                  followers:
                    type : number
                  follows:
                    type : number
                  date : 
                    type : date

  /sendUserInfo:

    post: 
      summary: return userName, email and password of user.
      responses :
        '200' : #status code
          description: return an object with cradentials about the user.
          content:
            application/json:
              schema:
                type : object
                properties:
                  userName:
                    type : string
                  email:
                    type : string
                  password:
                    type : string

  /twitter:
    get: 
      summary: return twitter userName, follower and follow with Data.
      responses :
        '200' : #status code
          description: return an object with information about the user.
          content:
            application/json:
              schema:
                type : object
                properties:
                  userName:
                    type : string
                  followers:
                    type : number
                  follows:
                    type : number
                  date : 
                    type : date

  /linkedin:
    get: 
      summary: return linkedin userName, follower and follow with Data.
      responses :
        '200' : #status code
          description: return an object with information about the user.
          content:
            application/json:
              schema:
                type : object
                properties:
                  userName:
                    type : string
                  followers:
                    type : number
                  follows:
                    type : number
                  date : 
                    type : date


  /{userId}:
    get: 
      summary: return userId of the user (Dynamic route example).
      parameters:
      - name : userId
        default : 191147
        in : path
        schema : 
          type : string
      responses :
        '200' : #status code
          description: return an object with information about the user.
          content:
            application/json:
              schema:
                type : object
                properties:
                  params:
                    type : string